# Generated by Django 4.1.4 on 2023-01-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailmail',
            old_name='email',
            new_name='email1',
        ),
    ]
